on: push
name: job_name
jobs:
  slack_msg:
    runs-on: ubuntu-latest
    steps:
    - name: Making_checkout
    - uses: actions/checkout@v2
    - name: Slack_step
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:, you rock!'
        SLACK_TITLE: Robot Message
