on: push
jobs:
  job1_title_slack_msg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: job1_step1_msg
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:, you rock! 1111'
        SLACK_TITLE: Robot Message
        
    - name: job1_step2_msg
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:, you rock! 2222'
        SLACK_TITLE: Robot Message
